name: Deploy Free VPS with Cockpit and ngrok

on:
  workflow_dispatch:

jobs:
  deploy-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Update System
        run: sudo apt-get update -y

      - name: Install Cockpit
        run: |
          sudo apt-get install -y cockpit
          sudo systemctl start cockpit
          sudo systemctl enable cockpit

      - name: Create User for Cockpit
        run: |
          sudo useradd -m -s /bin/bash vpsadmin
          echo "vpsadmin:SecureP@ssw0rd" | sudo chpasswd

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null \
          && sudo apt-get update && sudo apt-get install ngrok

      - name: Start ngrok Tunnel
        run: |
          ngrok config add-authtoken ${{ secrets.2HG0KabhUAcYzU7lhvlVdgRObB6_4UpZFUy3DKhXBDB2BQMsk }}
          ngrok http 9090 > ngrok.log &
          sleep 5
          cat ngrok.log | grep "https://" || echo "ngrok failed"

      - name: Keep Workflow Running
        run: sleep 600
