name: Deploy Free VPS

on: 
  workflow_dispatch:

jobs:
  deploy-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Set up VPS Environment
        run: |
          echo "Updating system packages..."
          sudo apt-get update -y
          sudo apt-get install -y openssh-server

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Ubuntu Docker Image
        run: docker pull ubuntu:20.04

      - name: Start VPS-like Container with SSH
        run: |
          docker run -d --name my_vps -p 2222:22 ubuntu:20.04 sleep infinity
          docker exec my_vps apt update
          docker exec my_vps apt install -y openssh-server
          docker exec my_vps service ssh start
          echo "VPS-like container is up and running!"

      - name: Check Docker Status
        run: docker ps
