name: Deploy Free VPS with Cockpit

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Schedule daily run at 12:00 UTC

jobs:
  deploy-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Update System Packages
        run: |
          echo "Updating system packages..."
          sudo apt-get update -y
          sudo apt-get install -y wget curl net-tools htop cockpit

      - name: Enable and Start Cockpit
        run: |
          echo "Starting Cockpit service..."
          sudo systemctl enable --now cockpit
          sudo systemctl status cockpit

      - name: Set Admin User and Password
        run: |
          echo "Creating user for Cockpit..."
          sudo useradd -m cockpitadmin
          echo 'cockpitadmin:SecurePassword123!' | sudo chpasswd
          echo "cockpitadmin ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/cockpitadmin
          echo "User cockpitadmin created with password: SecurePassword123!"

      - name: Keep the VPS Running
        run: |
          echo "Cockpit should now be accessible at port 9090."
          echo "Username: cockpitadmin | Password: SecurePassword123!"
          echo "Waiting for the environment to stay active..."
          sleep 7200 # Keep the job alive for 2 hours

